name: Node CI PR verify pipeline

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  test_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install dependencies
        run: yarn
        working-directory: client
      - name: Lint source code
        run: yarn lint
        working-directory: client
      - name: Run test suite
        run: yarn test:unit
        working-directory: client
      - name: Build for production
        run: yarn build --modern
        working-directory: client
    env:
      CI: true
  test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Install dependencies
        run: yarn
        working-directory: server
      - name: Lint source code
        run: yarn lint
        working-directory: server
      - name: Run test suite
        run: yarn test
        working-directory: server
      - name: Build for production
        run: yarn build
        working-directory: server
    env:
      CI: true
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
  automerge:
    runs-on: ubuntu-latest
    needs: [test_client, test_server]
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "!work in progress"
